version: "3"
services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
  backend:
    build: ./backend
    volumes:
      - ./backend/docs:/app/docs
      - ./backend/vectorstore:/app/vectorstore
    ports:
      - "8000:8000"
    depends_on:
      - ollama
